### PR TITLE
[SMAN-93] In GeneralService, replace printStackTrace with logger

### LINKED ISSUE #24: [SMAN-93] In GeneralService, replace printStackTrace with logger
In GeneralService in CsvFileReader, replace the 
exception.printStackTrace(); with logger, also add the logged to the class

### PR DESCRIPTION
**Pull request by radu1351**
CR URL: https://jira.harman.com/jira/browse/SMAN-93
CHANGES: Added exception logger to CsvFileReader readFile function
TESTING: No testing required

### CODE REVIEW

File: src/main/java/utils/filereaders/CsvFileReader.java [hunk 1]
```diff
@@ -9,9 +10,13 @@
 import java.util.ArrayList;
 import java.util.Arrays;
 import java.util.List;
+import org.apache.logging.log4j.LogManager;
+import org.apache.logging.log4j.Logger;
 
 public class CsvFileReader implements CustomFileReader {
 
+    private static final Logger logger = LogManager.getLogger(CsvFileReader.class);
```
Comment (sebi1995) [inline src/main/java/utils/filereaders/CsvFileReader.java]: UPPER_CASE the variable name, all static constant variables must have uppercase letters

**Review by sebi1995 — CHANGES_REQUESTED** [review]

**Review by sebi1995 — APPROVED** [review]
